In [41]:
import pandas as pd
import os

In [42]:
student_name = input('Inserte el nombre del estudiante (APELLIDO Nombre): ')
base_path = 'C:\\Users\\confi\\Richporter Lighting\\Operations Select - Documents\\01. Airplane\\03. Licenses Emissions (A)\\02. Airplane Students Records\\'
student_path = os.path.join(base_path, student_name,'CPL BALANCE',f'PTR-{student_name}.xlsx')
df = pd.read_excel(student_path, header=None)
df

Inserte el nombre del estudiante (APELLIDO Nombre):  PINTO Andrey

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Times summary of PINTO Andrey-929537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Course: ATP(A) 2019-FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Title only printout Selected phases: All phases,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2024-10-21,ALSIMALX,NBO,TEOLI R,ATP-S5-SIM7,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,2024-10-22,ALSIMALX,NBO,MCDONALD M,ATP-S5-SIM8,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,2024-10-24,ALSIMALX,NBO,MCDONALD M,ATP-S5-CK-SIM9,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,2024-11-07,C150,C-GQHU,PINTO A,CPL-S4-SF5,CYND,CYND,NaN,1.6,NaN,...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
182,2024-11-09,C150,C-GNLY,CUSACH R,CPL-S4-DF6-FT1,CYND,CYND,1.6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
new_row = ['Date','Type','Registration','Pic/Copic','Description','From','To','SE_day_dual','SE_day_pic','SE_night_dual','SE_night_pic','ME_day_dual','ME_day_pic','ME_day_copic','ME_night_dual','ME_night_pic','ME_night_copic','IMC','Hood','FTD','ifr appr','x-country_day_dual','x_country_day_pic','x-country_night_dual','x-country_night_pic','T/O_day','T/O_night','VFR_FTD','Theory','PGI','Studies','Exams']
new_row_df = pd.DataFrame([new_row])
df = df.reset_index(drop=True)
new_row_df = new_row_df.reset_index(drop=True)
df = pd.concat([new_row_df,df], ignore_index = True)
df.columns = df.iloc[0]
df = df.drop(0).reset_index(drop=True)
df = df.iloc[9:].reset_index(drop=True)
df = df.iloc[:, :-4]
df

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,Hood,FTD,ifr appr,x-country_day_dual,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD
0,2022-04-04,C150,C-GAQH,CASTANEDA S,PPL-S1-DF1,CYND,CYND,1.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1,2022-04-05,ALSIMAL250,BOG,CASTANEDA S,PPL-S1-SIM1*,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3
2,2022-04-09,C150,C-GNBI,CASTANEDA S,PPL-S1-DF2,CYND,CYND,1.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
3,2022-04-11,ALSIMAL250,YUL,CASTANEDA S,PPL-S1-SIM2*,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5
4,2022-04-18,C150,C-FTPX,CASTANEDA S,PPL-S1-DF3,CYND,CYND,1.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,2024-10-21,ALSIMALX,NBO,TEOLI R,ATP-S5-SIM7,CYND,CYND,NaN,NaN,NaN,...,NaN,4,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,2024-10-22,ALSIMALX,NBO,MCDONALD M,ATP-S5-SIM8,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,2024-10-24,ALSIMALX,NBO,MCDONALD M,ATP-S5-CK-SIM9,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,2024-11-07,C150,C-GQHU,PINTO A,CPL-S4-SF5,CYND,CYND,NaN,1.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
173,2024-11-09,C150,C-GNLY,CUSACH R,CPL-S4-DF6-FT1,CYND,CYND,1.6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
#df filtrados

In [45]:
df_ppl = df[df['Description'].str.contains('PPL', na=False)]
df_ft_ppl = df_ppl[df_ppl['Description'].str.contains('FT', na=False)]
df_vfr = df[df['Description'].str.contains('S3',na=False) & ~df['Type'].str.contains('PA44',na=False)]
df_cpl = df[df['Description'].str.contains('S4',na=False)]
df_ft_cpl = df_cpl[df_cpl['Description'].str.contains('FT', na=False)]
df_multi = df[df['Description'].str.contains('IRME',na=False) | df['Description'].str.contains('Multi',na=False)]
df_multi_ft = df[df['Description'].str.contains('IRME',na=False) &  df['Description'].str.contains('FT',na=False)| df['Description'].str.contains('Multi',na=False) &  df['Description'].str.contains('FT',na=False)]
df_c172 = df[df['Type'].str.contains('C172',na=False)]
df_int = df[df['Description'].str.contains('S5',na=False)]

In [46]:
#calcula fase PPL

In [75]:
dual_hours_ppl = round(df_ppl['SE_day_dual'].sum() + df_ppl['SE_night_dual'].sum() - df_ft_ppl['SE_day_dual'].sum(),2)
solo_hours_ppl = round(df_ppl['SE_day_pic'].sum() + df_ppl['SE_night_pic'].sum(),2)
ft_hours_ppl = round(df_ft_ppl['SE_day_dual'].sum(),2)
sim_hours_ppl = round(df_ppl['VFR_FTD'].sum() + df_ppl['FTD'].sum(),2)
print('In the main PTR, PPL phase: ')
print(f'{dual_hours_ppl} hours of duals')
print(f'{solo_hours_ppl} hours of solo')
print(f'{ft_hours_ppl} hours of Flight Test')
print(f'{sim_hours_ppl} hours of simulator')

In the main PTR, PPL phase:
39.8 hours of duals
15.7 hours of solo
1.9 hours of Flight Test
13.7 hours of simulator

In [48]:
#calcula fase VFR

In [49]:
dual_hours_vfr = round(df_vfr['SE_day_dual'].sum() + df_vfr['SE_night_dual'].sum(),2)
solo_hours_vfr = round(df_vfr['SE_day_pic'].sum() + df_vfr['SE_night_pic'].sum(),2)
sim_hours_vfr = round(df_vfr['VFR_FTD'].sum() + df_vfr['FTD'].sum(),2)
dual_hours_ifr = round(df_multi['ME_day_dual'].sum() + df_multi['ME_night_dual'].sum()-df_multi_ft['ME_day_dual'].sum(),2)
ft_ifr_hours = round(df_multi_ft['ME_day_dual'].sum(),2)
print('In the main PTR, VFR phase: ')
print(f'{dual_hours_vfr} hours of duals')
print(f'{solo_hours_vfr} hours of solo')
print(f'{sim_hours_vfr} hours of simulator')
print(f'{dual_hours_ifr} hours of duals in PA44')
print(f'{ft_ifr_hours} hours of Flight Test in PA44')

In the main PTR, VFR phase:
19.4 hours of duals
54.1 hours of solo
39.1 hours of simulator
19.6 hours of duals in PA44
2.9 hours of Flight Test in PA44

In [50]:
#Calcula Fase CPL

In [51]:
dual_hours_cpl = round(df_cpl['SE_day_dual'].sum() + df_cpl['SE_night_dual'].sum() - df_ft_cpl['SE_day_dual'].sum(),2)
solo_hours_cpl = round(df_cpl['SE_day_pic'].sum() + df_cpl['SE_night_pic'].sum(),2)
ft_hours_cpl = round(df_ft_cpl['SE_day_dual'].sum(),2)
print('In the main PTR, CPL phase: ')
print(f'{dual_hours_cpl} hours of duals')
print(f'{solo_hours_cpl} hours of solos')
print(f'{ft_hours_cpl} hours of Flight Test')

In the main PTR, CPL phase:
9.5 hours of duals
24.0 hours of solos
1.6 hours of Flight Test

In [77]:
solo_hours_int = round(df_int['SE_day_pic'].sum()+ df_int['SE_night_pic'].sum(),2)
sim_int = round(df_int['VFR_FTD'].sum()+df_int['FTD'].sum(),2)
print('In the main PTR, integrated phase: ')
print(f'{solo_hours_int} hours of solo')
print(f'{sim_int} hours of sim')

In the main PTR, integrated phase:
5.7 hours of solo
36 hours of sim

In [53]:
#PTR Adicional

In [54]:
student_path2 = os.path.join(base_path, student_name,'CPL BALANCE',f'PTR ADD-{student_name}.xlsx')
df2 = pd.read_excel(student_path2, header = None)
new_row_df2 = pd.DataFrame([new_row])
df2 = df2.reset_index(drop=True)
new_row_df2 = new_row_df2.reset_index(drop=True)
df2 = pd.concat([new_row_df2,df2], ignore_index = True)
df2.columns = df2.iloc[0]
df2 = df2.drop(0).reset_index(drop=True)
df2 = df2.iloc[9:].reset_index(drop=True)
df2

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD,Theory,PGI,Studies,Exams
0,2023-04-10,C150,C-GUGC,TOVAR S,PPL-REV-DF,CYND,CYND,0.6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-05-25,C150,C-GNBI,CASTANEDA S,PPL-REV-DF,CYND,CYND,1.1,NaN,NaN,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-05-29,C150,C-GNBI,CASTANEDA S,PPL-REV-DF,CYND,CYND,1.8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-07-12,C150,C-GPUY,REPPERT J,PPL-REV-DF,CYND,CYND,NaN,NaN,0.5,...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
4,2023-10-29,C150,C-GDXD,PINTO A,CPL-REV-SF,CYND,CYND,NaN,0.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2023-12-05,GROUPCLASS,CDG,BALLE H,TC exam - Review class,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN
6,2023-12-05,GROUPCLASS,CDG,BALLE H,TC exam - Review class,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN
7,2024-03-08,C172,C-GXGF,BALAREZO N,PPL-REV-DF,CYND,CYND,0.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-07-18,C172,C-GXGF,HARO J,CPL-REV-DF,CYND,CYND,0.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-08-14,C150,C-GNLY,HARO J,CPL-REV-DF,CYND,CYND,0.4,NaN,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2024-09-04,ALSIMAL250,YUL,HARO J,MIFR-REV-SIM,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2024-09-16,C150,C-GRWH,HARO J,CPL-REV-DF,CYND,CYND,NaN,NaN,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-10-17,C150,C-GNLY,PINTO A,CPL-REV-SF,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN
13,2024-11-03,C150,C-FTOD,HARO J,CPL-REV-DF,CYND,CYND,1.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df_ft_add = df2[df2['Description'].str.contains('FT', na=False)]
df_c172_add = df2[df2['Type'].str.contains('C172', na=False)]

In [56]:
dual_hours_add = round(df2['SE_day_dual'].sum() + df2['SE_night_dual'].sum() - df_ft_add['SE_day_dual'].sum(),2)
solo_hours_add = round(df2['SE_day_pic'].sum() + df2['SE_night_pic'].sum(),2)
ft_hours_add = round(df_ft_add['SE_day_dual'].sum(),2)
sim_hours_add = round(df2['VFR_FTD'].sum() + df2['FTD'].sum(),2)
print('En el PTR Adicional: ')
print(f'Tiene {dual_hours_add} horas de duales')
print(f'Tiene {solo_hours_add} horas de solo')
print(f'Tiene {ft_hours_add} horas de Flight Test')
print(f'Tiene {sim_hours_add} horas de simulador')

En el PTR Adicional:
Tiene 8.4 horas de duales
Tiene 1.0 horas de solo
Tiene 0 horas de Flight Test
Tiene 1.5 horas de simulador

In [57]:
c172_hours = round(df_c172['SE_day_dual'].sum() + df_c172['SE_night_dual'].sum() + df_c172['SE_day_pic'].sum() + df_c172['SE_night_pic'].sum() + df_c172_add['SE_day_dual'].sum()+df_c172_add['SE_night_dual'].sum()+df_c172_add['SE_night_pic'].sum()+df_c172_add['SE_day_pic'].sum())
print(f'Tiene {c172_hours} horas en C172')

Tiene 14 horas en C172