In [18]:
import pandas as pd
import os

In [19]:
student_name = input('Inserte el nombre del estudiante: ')
base_path = 'C:\\Users\\confi\\Richporter Lighting\\Operations Select - Documents\\01. Airplane\\03. Licenses Emissions (A)\\02. Airplane Students Records\\'
student_path = os.path.join(base_path, student_name,'CPL',f'PTR-{student_name}.xlsx')
df = pd.read_excel(student_path, header=None)
df

Inserte el nombre del estudiante:  ESCALONA Jose

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Times summary of ESCALONA Jose-930336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Course: ATP(A) 2019-FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Title only printout Selected phases: All phases,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,2024-06-06,ALSIMALX,NBO,SNOUSSI T,ATP-S5-SIM7,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,2024-06-07,ALSIMALX,NBO,SNOUSSI T,ATP-S5-SIM8,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,2024-06-07,ALSIMALX,NBO,SNOUSSI T,ATP-S5-CK-SIM9,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,2024-06-16,C150,C-GHQS,ESCALONA J,ATP-S5-SF-CYPQ,CYND,CYGK,NaN,1.9,NaN,...,1.9,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
176,2024-06-16,C150,C-GHQS,ESCALONA J,ATP-S5-SF-CYPQ,CYGK,CYND,NaN,1.6,NaN,...,1.6,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
new_row = ['Date','Type','Registration','Pic/Copic','Description','From','To','SE_day_dual','SE_day_pic','SE_night_dual','SE_night_pic','ME_day_dual','ME_day_pic','ME_day_copic','ME_night_dual','ME_night_pic','ME_night_copic','IMC','Hood','FTD','ifr appr','x-country_day_dual','x_country_day_pic','x-country_night_dual','x-country_night_pic','T/O_day','T/O_night','VFR_FTD','Theory','PGI','Studies','Exams']
new_row_df = pd.DataFrame([new_row])
df = df.reset_index(drop=True)
new_row_df = new_row_df.reset_index(drop=True)
df = pd.concat([new_row_df,df], ignore_index = True)
df.columns = df.iloc[0]
df = df.drop(0).reset_index(drop=True)
df = df.iloc[9:].reset_index(drop=True)
df = df.iloc[:, :-4]
df

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,Hood,FTD,ifr appr,x-country_day_dual,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD
0,2022-07-15,C150,C-GFVI,CASTANEDA S,PPL-S1-DF1,CYND,CYND,1.1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-23,ALSIMAL250,BOG,CASTANEDA S,PPL-S1-SIM1*,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2022-07-23,C150,C-GAQH,CASTANEDA S,PPL-S1-DF2,CYND,CYND,1.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
3,2022-07-26,ALSIMAL250,BOG,CASTANEDA S,PPL-S1-SIM2*,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5
4,2022-07-27,C150,C-FTPX,CASTANEDA S,PPL-S1-DF3,CYND,CYND,1.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-06-06,ALSIMALX,NBO,SNOUSSI T,ATP-S5-SIM7,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2024-06-07,ALSIMALX,NBO,SNOUSSI T,ATP-S5-SIM8,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,2024-06-07,ALSIMALX,NBO,SNOUSSI T,ATP-S5-CK-SIM9,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,2024-06-16,C150,C-GHQS,ESCALONA J,ATP-S5-SF-CYPQ,CYND,CYGK,NaN,1.9,NaN,...,NaN,NaN,NaN,NaN,1.9,NaN,NaN,1,NaN,NaN
167,2024-06-16,C150,C-GHQS,ESCALONA J,ATP-S5-SF-CYPQ,CYGK,CYND,NaN,1.6,NaN,...,NaN,NaN,NaN,NaN,1.6,NaN,NaN,1,NaN,NaN

In [29]:
df_cpl = df[~df['Description'].str.contains('PPL', na=False)]

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,Hood,FTD,ifr appr,x-country_day_dual,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD
58,2023-08-25,C172,C-GXGF,CASTANEDA S,NR-S3-DF1*,CYND,CYND,NaN,NaN,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN
59,2023-08-27,C172,C-GXGF,ESCALONA J,CPL-S3-SF1-CYMX,CYND,CYND,NaN,1.9,NaN,...,NaN,NaN,NaN,NaN,1.9,NaN,NaN,1,NaN,NaN
60,2023-08-27,C172,C-GXGF,ESCALONA J,CPL-S3-SF3-CYRP,CYND,CYND,NaN,1.1,NaN,...,NaN,NaN,NaN,NaN,1.1,NaN,NaN,2,NaN,NaN
61,2023-08-28,C172,C-GWXV,ESCALONA J,CPL-S3-SF4-CNP3,CYND,CYND,NaN,1.4,NaN,...,NaN,NaN,NaN,NaN,1.4,NaN,NaN,3,NaN,NaN
62,2023-08-28,C172,C-GWXV,CASTANEDA S,NR-S3-DF3,CYND,CYND,0.2,NaN,2,...,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2024-06-06,ALSIMALX,NBO,SNOUSSI T,ATP-S5-SIM7,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2024-06-07,ALSIMALX,NBO,SNOUSSI T,ATP-S5-SIM8,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,2024-06-07,ALSIMALX,NBO,SNOUSSI T,ATP-S5-CK-SIM9,CYND,CYND,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,2024-06-16,C150,C-GHQS,ESCALONA J,ATP-S5-SF-CYPQ,CYND,CYGK,NaN,1.9,NaN,...,NaN,NaN,NaN,NaN,1.9,NaN,NaN,1,NaN,NaN
167,2024-06-16,C150,C-GHQS,ESCALONA J,ATP-S5-SF-CYPQ,CYGK,CYND,NaN,1.6,NaN,...,NaN,NaN,NaN,NaN,1.6,NaN,NaN,1,NaN,NaN

In [22]:
student_path2 = os.path.join(base_path, student_name,'CPL',f'PTR ADD-{student_name}.xlsx')
df2 = pd.read_excel(student_path2, header = None)
new_row_df2 = pd.DataFrame([new_row])
df2 = df2.reset_index(drop=True)
new_row_df2 = new_row_df2.reset_index(drop=True)
df2 = pd.concat([new_row_df2,df2], ignore_index = True)
df2.columns = df2.iloc[0]
df2 = df2.drop(0).reset_index(drop=True)
df2 = df2.iloc[9:].reset_index(drop=True)
df2

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD,Theory,PGI,Studies,Exams
0,2023-04-24,C150,C-GAQH,CASTANEDA S,PPL-REV-DF,CYND,CYND,0.7,NaN,NaN,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-08-01,C150,C-GBGM,KARIITHI B,PPL-REV-DF,CYND,CYND,1.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-08-25,C172,C-GXGF,CASTANEDA S,PPL-REV-DF,CYND,CYND,1.5,NaN,NaN,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-09-08,C172,C-GXGF,YONGBIAO G,PPL-REV-DF,CYND,CYND,NaN,NaN,1.1,...,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN
4,2023-10-19,C172,C-GXGF,YONGBIAO G,PPL-REV-DF,CYND,CYND,0.8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-03-14,C150,C-FTOD,ESCALONA J,CPL-REV-SF,CYND,CYND,NaN,0.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-03-24,C150,C-GNBI,ESCALONA J,CPL-REV-SF,CYND,CYND,NaN,2.2,NaN,...,2.2,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-06-14,C172,C-GWXV,ESCALONA J,CPL-REV-SF,CYND,CYND,NaN,3,NaN,...,2.3,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_cpl_add = df2[~df2['Description'].str.contains('PPL', na=False)]

In [49]:
total_flight_time = round(df_cpl['SE_day_dual'].sum() + df_cpl['SE_night_dual'].sum() + df_cpl_add['SE_day_dual'].sum()+df_cpl_add['SE_night_dual'].sum()+df_cpl['SE_day_pic'].sum() + df_cpl['SE_night_pic'].sum() + df_cpl_add['SE_day_pic'].sum()+ df_cpl_add['SE_night_pic'].sum(),2)
dual_day_hours = round(df_cpl['SE_day_dual'].sum() + df_cpl_add['SE_day_dual'].sum()+df_cpl['ME_day_dual'].sum()+ df_cpl_add['ME_day_dual'].sum() ,2)
dual_night_hours = round(df_cpl['SE_night_dual'].sum() + df_cpl['ME_night_dual'].sum()+ df_cpl_add['SE_night_dual'].sum() + df_cpl_add['ME_night_dual'].sum(),2)
solo_day_hours = round(df_cpl['SE_day_pic'].sum() + df_cpl_add['SE_day_pic'].sum()+df_cpl['ME_day_pic'].sum()+ df_cpl_add['ME_day_pic'].sum() ,2)
solo_night_hours = round(df_cpl['SE_night_pic'].sum() + df_cpl['ME_night_pic'].sum()+ df_cpl_add['SE_night_pic'].sum() + df_cpl_add['ME_night_pic'].sum(),2)
to_night = round(df_cpl['T/O_night'].sum() + df_cpl_add['T/O_night'].sum())
dual_day_cross_country = round(df_cpl['x-country_day_dual'].sum() +df_cpl_add['x-country_day_dual'].sum(),2)
dual_night_cross_country = round(df_cpl['x-country_night_dual'].sum()+df_cpl_add['x-country_night_dual'].sum(),2)
ins_flight_time = round(df_cpl['IMC'].sum() + df_cpl['Hood'].sum()+df_cpl_add['IMC'].sum() + df_cpl_add['Hood'].sum(),2)
ground_flight_time = round(df_cpl['FTD'].sum()+df_cpl_add['FTD'].sum(),2)
print('En el PTR: ')
print(f'Tiene {dual_day_hours} horas de dual day')
print(f'Tiene {solo_day_hours} horas de solo day')
print(f'Tiene {dual_night_hours} horas de dual night')
print(f'Tiene {solo_night_hours} horas de solo night')
print(f'Tiene {to_night} horas de take off and landings at night')
print(f'Tiene {dual_day_cross_country} horas de day duales en cross-country')
print(f'Tiene {dual_night_cross_country} horas de night duales en cross-country')
print(f'Tiene {ins_flight_time} horas de instrument time')
print(f'Tiene {ground_flight_time} horas de ground time')

En el PTR:
Tiene 45.6 horas de dual day
Tiene 80.4 horas de solo day
Tiene 5.9 horas de dual night
Tiene 5.0 horas de solo night
Tiene 38 horas de take off and landings at night
Tiene 8.1 horas de day duales en cross-country
Tiene 2.9 horas de night duales en cross-country
Tiene 19.9 horas de instrument time
Tiene 75.9 horas de ground time