In [1]:
import pandas as pd
import os

In [2]:
student_name = input('Inserte el nombre del estudiante: ')
base_path = 'C:\\Users\\confi\\Richporter Lighting\\Operations Select - Documents\\01. Airplane\\03. Licenses Emissions (A)\\02. Airplane Students Records\\'
student_path = os.path.join(base_path, student_name,'PPL',f'PTR-{student_name}.xlsx')
df = pd.read_excel(student_path, header=None)
df

Inserte el nombre del estudiante:  SOKA Razaq

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Times summary of SOKA Razaq-932314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Course: ATP(A) 2019-FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Title only printout Selected phases: All phases,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,2024-08-15,C172,C-GWXV,PATNAIK A,NR-S3-DF3,CYND,CYND,NaN,NaN,2.6,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,2024-09-10,C172,C-GWXV,SOKA R,NR-S3-SF1,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2024-09-11,C172,C-GWXV,SOKA R,NR-S3-SF2,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,2024-09-12,C172,C-GXGF,SOKA R,NR-S3-SF3,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,2024-09-12,C172,C-GXGF,SOKA R,NR-S3-SF4,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
new_row = ['Date','Type','Registration','Pic/Copic','Description','From','To','SE_day_dual','SE_day_pic','SE_night_dual','SE_night_pic','ME_day_dual','ME_day_pic','ME_day_copic','ME_night_dual','ME_night_pic','ME_night_copic','IMC','Hood','FTD','ifr appr','x-country_day_dual','x_country_day_pic','x-country_night_dual','x-country_night_pic','T/O_day','T/O_night','VFR_FTD','Theory','PGI','Studies','Exams']
new_row_df = pd.DataFrame([new_row])
df = df.reset_index(drop=True)
new_row_df = new_row_df.reset_index(drop=True)
df = pd.concat([new_row_df,df], ignore_index = True)
df.columns = df.iloc[0]
df = df.drop(0).reset_index(drop=True)
df = df.iloc[9:].reset_index(drop=True)
df = df.iloc[:, :-4]
df

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,Hood,FTD,ifr appr,x-country_day_dual,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD
0,2023-09-23,C150,C-GDXD,HARO J,PPL-S1-DF1,CYND,CYND,1.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-09-27,ALSIMAL250,YUL,HARO J,PPL-S1-SIM1*,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2023-10-03,C150,C-GFVI,HARO J,PPL-S1-DF2,CYND,CYND,1.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-10-08,ALSIMAL250,YUL,HARO J,PPL-S1-SIM2*,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3
4,2023-10-17,C150,C-FUAE,HARO J,PPL-S1-DF3,CYND,CYND,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2024-08-15,C172,C-GWXV,PATNAIK A,NR-S3-DF3,CYND,CYND,NaN,NaN,2.6,...,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN
64,2024-09-10,C172,C-GWXV,SOKA R,NR-S3-SF1,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,2024-09-11,C172,C-GWXV,SOKA R,NR-S3-SF2,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,2024-09-12,C172,C-GXGF,SOKA R,NR-S3-SF3,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,2024-09-12,C172,C-GXGF,SOKA R,NR-S3-SF4,CYND,CYND,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_ppl = df[df['Description'].str.contains('PPL', na=False)]

In [5]:
student_path2 = os.path.join(base_path, student_name,'PPL',f'PTR ADD-{student_name}.xlsx')
df2 = pd.read_excel(student_path2, header = None)
new_row_df2 = pd.DataFrame([new_row])
df2 = df2.reset_index(drop=True)
new_row_df2 = new_row_df2.reset_index(drop=True)
df2 = pd.concat([new_row_df2,df2], ignore_index = True)
df2.columns = df2.iloc[0]
df2 = df2.drop(0).reset_index(drop=True)
df2 = df2.iloc[9:].reset_index(drop=True)
df2

,Date,Type,Registration,Pic/Copic,Description,From,To,SE_day_dual,SE_day_pic,SE_night_dual,...,x_country_day_pic,x-country_night_dual,x-country_night_pic,T/O_day,T/O_night,VFR_FTD,Theory,PGI,Studies,Exams
0,2024-02-20,C150,C-GRAE,HARO J,PPL-REV-DF,CYND,CYND,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-02-27,C150,C-GUDB,SOKA R,PPL-REV-SF,CYND,CYND,NaN,1,NaN,...,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-04-16,C150,C-GNLY,HARO J,PPL-REV-DF,CYND,CYND,1.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-05-02,C150,C-GNUQ,CHOHAN P,PPL-REV-DF,CYND,CYND,0.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-25,C150,C-GNUQ,AYODELE-ALE O,PPL-REV-DF,CYND,CYND,0.9,NaN,NaN,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-07-03,C150,C-GRWH,AYODELE-ALE O,PPL-REV-DF,CYND,CYND,1.5,NaN,NaN,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-09-10,C172,C-GWXV,PATNAIK A,CPL-REV-DF,CYND,CYND,NaN,NaN,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_ppl_add = df2[df2['Description'].str.contains('PPL', na=False)]

In [15]:
total_flight_time = round(df_ppl['SE_day_dual'].sum() + df_ppl['SE_night_dual'].sum() + df_ppl_add['SE_day_dual'].sum()+df_ppl_add['SE_night_dual'].sum()+df_ppl['SE_day_pic'].sum() + df_ppl['SE_night_pic'].sum() + df_ppl_add['SE_day_pic'].sum()+ df_ppl_add['SE_night_pic'].sum(),2)
dual_hours = round(df_ppl['SE_day_dual'].sum() + df_ppl['SE_night_dual'].sum() + df_ppl_add['SE_day_dual'].sum()+df_ppl_add['SE_night_dual'].sum(),2)
solo_hours = round(df_ppl['SE_day_pic'].sum() + df_ppl['SE_night_pic'].sum() + df_ppl_add['SE_day_pic'].sum()+ df_ppl_add['SE_night_pic'].sum(),2)
dual_cross_country = round(df_ppl['x-country_day_dual'].sum() + df_ppl['x-country_night_dual'].sum()+df_ppl_add['x-country_day_dual'].sum()+df_ppl_add['x-country_night_dual'].sum(),2)
solo_cross_country = round(df_ppl['x_country_day_pic'].sum() + df_ppl['x-country_night_pic'].sum()+df_ppl_add['x_country_day_pic'].sum()+df_ppl_add['x-country_night_pic'].sum() ,2)
ins_flight_time = round(df_ppl['IMC'].sum() + df_ppl['Hood'].sum()+df_ppl_add['IMC'].sum() + df_ppl_add['Hood'].sum(),2)
ground_flight_time = round(df_ppl['FTD'].sum()+df_ppl_add['FTD'].sum(),2)
print('En el PTR: ')
print(f'Tiene {total_flight_time} horas de total flight time')
print(f'Tiene {dual_hours} horas de duales')
print(f'Tiene {solo_hours} horas de solo')
print(f'Tiene {dual_cross_country} horas de duales en cross-country')
print(f'Tiene {solo_cross_country} horas de solo en cross-country')
print(f'Tiene {ins_flight_time} horas de instrument time')
print(f'Tiene {ground_flight_time} horas de ground time')

En el PTR:
Tiene 62.3 horas de total flight time
Tiene 46.3 horas de duales
Tiene 16.0 horas de solo
Tiene 7.9 horas de duales en cross-country
Tiene 7.4 horas de solo en cross-country
Tiene 5.3 horas de instrument time
Tiene 3 horas de ground time